### PR TITLE
E0d/update actions

### PR DESCRIPTION
**Pull request by e0d**
**Description:**

This PR updates two actions to their latest version for new XBlocks.  I've tests this on the DoneXBlock and it worked there.

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

### CODE REVIEW

**Review by sarina — APPROVED** [review]
Is it worth updating https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-django-app/%7B%7Bcookiecutter.repo_name%7D%7D/.github/workflows/ci.yml#L41 as well?

**Comment by e0d** [comment]
@sarina on further review of the codecov breaking changes, it's just the removal of some arguments that we are not using.  I've pushed commits to update all the remaining references.

**Comment by e0d** [comment]
@timmc-edx and/or @rgraber if this looks good to you I'll merge.

**Review by timmc-edx — APPROVED** [review]
If these versions are working in other repos then it looks fine to me!

**Pull request merged**
